name: CD Frontend Angular

on:
  push:
    branches:
      - main   # ce pipeline se déclenche uniquement sur main

jobs:
  build-and-docker:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci

      - name: Build Angular App (Production)
        run: npx ng build --configuration production

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile   # le Dockerfile doit être dans le dossier front/
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/monapp-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/monapp-frontend:${{ github.sha }}
